### ISSUE TITLE
Only -inf and inf results

### ISSUE THREAD

**Issue by rafael2k** [AlirezaJav/Point_to_distribution_metric#1]
Hi,
When running the code I only get (eg):
pc_error -a amphoriskos_vox10_hidden.ply -b amphoriskos_vox10_octree10_jpeg010.ply -c 1 -d 1 --nbThreads=16
(...)
   mmd       (p2distr): inf
   mmd,PSNR  (p2distr): -inf
   msmd      (p2distr): inf
   msmd,PSNR (p2distr): -inf
(...)

I always get -inf and inf as result for both mmd and msmd.

Other metrics work fine.

**Comment by AlirezaJav** [comment]
Would you give me some information about your PCs? First of all, the contents should be voxelized. The metric is not tested and adjusted for floating-point data. Second, this is an only geometry metric, so if your PCs have the same geometry and the color is distorted, of course, you are comparing similar signals. Your filenames show that there are not any of these issues, but it's good to be sure.
P.S. The color metric will be added soon. Currently, it supports only geometry distortions.

**Comment by rafael2k** [comment]
Oi,
Acho que nos vimos numa conferência!
; )
My PCs are float 64, which I load in mpeg pc_error though a patch I committed in a fork of yours. May be this is the problem? Can you just give me a PC ply sample which works and I can play with?

**Comment by AlirezaJav** [comment]
yes, we talked in ICIP. 
This is exactly the problem. voxelize the PCs yourself or use PCs in one these datasets. [M-PCCD](https://www.epfl.ch/labs/mmspg/downloads/quality-assessment-for-point-cloud-compression/) or [IRPC-Dataset](https://github.com/AlirezaJav/IRPC-Dataset)

**Comment by rafael2k** [comment]
Tks!
